import Fit from './Fit';

enum FitBaseType {
  ENUM = Fit.BASE_TYPE_ENUM,
  SINT8 = Fit.BASE_TYPE_SINT8,
  UINT8 = Fit.BASE_TYPE_UINT8,
  SINT16 = Fit.BASE_TYPE_SINT16,
  UINT16 = Fit.BASE_TYPE_UINT16,
  SINT32 = Fit.BASE_TYPE_SINT32,
  UINT32 = Fit.BASE_TYPE_UINT32,
  STRING = Fit.BASE_TYPE_STRING,
  FLOAT32 = Fit.BASE_TYPE_FLOAT32,
  FLOAT64 = Fit.BASE_TYPE_FLOAT64,
  UINT8Z = Fit.BASE_TYPE_UINT8Z,
  UINT16Z = Fit.BASE_TYPE_UINT16Z,
  UINT32Z = Fit.BASE_TYPE_UINT32Z,
  BYTE = Fit.BASE_TYPE_BYTE,
  SINT64 = Fit.BASE_TYPE_SINT64,
  UINT64 = Fit.BASE_TYPE_UINT64,
  UINT64Z = Fit.BASE_TYPE_UINT64Z,
}
export default FitBaseType;
